name: grocery_app
description: A Grocery Project project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  awesome_icons: ^1.1.0
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: null
  get_it: ^7.6.0
  google_sign_in: ^6.1.3
  location: ^4.4.0
  otp_text_field: ^1.1.3
  percent_indicator: ^4.2.3
  shared_preferences: ^2.1.1
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
